---
services:
  homeassistant:
    container_name: very-dark-black-ha-dev
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      # Mount the whole project so the DevContainer workspace works
      - ..:/workspaces/very-dark-black-ha-theme
      # Mount your local dev config
      - ./.devconfig:/config
      # Maps your theme file into the HA themes folder
      # Note: The folder inside /config must be named 'themes'
      - ../themes:/config/themes
    ports:
      - "8123:8123"
    restart: unless-stopped
    environment:
      - TZ=Europe/London
